# docker composerのバージョンの指定
version: "3.8" 
services:
  front:
    # buildするdockerfileの位置
    build: ./
    # 作成するdockerコンテナの名前
    container_name: hipFront
    volumes:
      # docker内と共有するフォルダの指定
      - ./front:/front
    # docker内に入った時の初期パスの指定
    working_dir: /front
    ports:
      # コンテナにバインドするポートの指定（左:自分のPCポート、右:dookerコンテナのポート）
      - 3000:3000
    # コンテナが勝手に終了しないための設定
    tty: true
    # 標準入出力とエラー出力をコンテナに結びつける設定
    stdin_open: true
    environment:
      # ホットリロードを行う設定
      - CHOKIDAR_USEPOLLING=true